# Generated by Django 5.0.3 on 2024-06-13 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
