# Generated by Django 5.0.3 on 2024-06-28 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Quizzy", "0001_initial"),
        ("api", "0007_quiz_date_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaderboard",
            old_name="User",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                fields=("quiz", "user"), name="unique_quiz_user"
            ),
        ),
    ]
